import {
  austriaFlag,
  belgiumFlag,
  beninFlag,
  burkinaFlag,
  camerounFlag,
  canadaFlag,
  chinaFlag,
  ciFlag,
  croatiaFlag,
  cyprusFlag,
  englandFlag,
  estoniaFlag,
  finlandFlag,
  frenchFlag,
  germanyFlag,
  greeceFlag,
  italyFlag,
  lettoniaFlag,
  lithuaniaFlag,
  luxemburgFlag,
  maliFlag,
  maltaFlag,
  netherlandFlag,
  nigeriaFlag,
  portugalFlag,
  senegalFlag,
  slovakiaFlag,
  sloveniaFlag,
  spainFlag,
  togoFlag,
  uaeFlag,
  usaFlag,
} from "../constants/appConstants";

export const currenciesReception = [
  {
    currency: "EUR",
    country: "EUR - France",
    flag: frenchFlag,
    countryCode: "FR",
  },
  {
    currency: "EUR",
    country: "EUR - Allemagne",
    flag: germanyFlag,
    countryCode: "DE",
  },
  {
    currency: "EUR",
    country: "EUR - Portugal",
    flag: portugalFlag,
    countryCode: "PT",
  },
  {
    currency: "EUR",
    country: "EUR - Espagne",
    flag: spainFlag,
    countryCode: "ES",
  },
  {
    currency: "EUR",
    country: "EUR - Belgique",
    flag: belgiumFlag,
    countryCode: "BE",
  },
  {
    currency: "USD",
    country: "USD - United States of America",
    flag: usaFlag,
    countryCode: "US",
  },
  {
    currency: "GBP",
    country: "GBP - United Kingdom",
    flag: englandFlag,
    countryCode: "GB",
  },
  {
    currency: "CNY",
    country: "CNY - China",
    flag: chinaFlag,
    countryCode: "CN",
  },
  {
    currency: "AED",
    country: "AED - United Arab Emirates",
    flag: uaeFlag,
    countryCode: "AE",
  },
  {
    currency: "CAD",
    country: "CAD - Canada",
    flag: canadaFlag,
    countryCode: "CA",
  },
  {
    currency: "EUR",
    country: "EUR - Italie",
    flag: italyFlag,
    countryCode: "IT",
  },
  {
    currency: "EUR",
    country: "EUR - Croatie",
    flag: croatiaFlag,
    countryCode: "HR",
  },
  {
    currency: "EUR",
    country: "EUR - Autriche",
    flag: austriaFlag,
    countryCode: "AT",
  },

  {
    currency: "EUR",
    country: "EUR - Grece",
    flag: greeceFlag,
    countryCode: "GR",
  },
  {
    currency: "EUR",
    country: "EUR - Finlande",
    flag: finlandFlag,
    countryCode: "FI",
  },
  {
    currency: "EUR",
    country: "EUR - Pays Bas",
    flag: netherlandFlag,
    countryCode: "NL",
  },
  {
    currency: "EUR",
    country: "EUR - Luxembourg",
    flag: luxemburgFlag,
    countryCode: "LU",
  },
  {
    currency: "EUR",
    country: "EUR - Lithuanie",
    flag: lithuaniaFlag,
    countryCode: "LT",
  },
  {
    currency: "EUR",
    country: "EUR - Lettonie",
    flag: lettoniaFlag,
    countryCode: "LV",
  },
  {
    currency: "EUR",
    country: "EUR - Chypre",
    flag: cyprusFlag,
    countryCode: "CY",
  },
  {
    currency: "EUR",
    country: "EUR - Estonie",
    flag: estoniaFlag,
    countryCode: "EE",
  },
  {
    currency: "EUR",
    country: "EUR - Slovakie",
    flag: slovakiaFlag,
    countryCode: "SK",
  },
  {
    currency: "EUR",
    country: "EUR - Slovenie",
    flag: sloveniaFlag,
    countryCode: "SI",
  },
  {
    currency: "EUR",
    country: "EUR - Malte",
    flag: maltaFlag,
    countryCode: "MT",
  },
  {
    currency: "NGN",
    country: "NGN - Nigeria",
    flag: nigeriaFlag,
    countryCode: "NG",
  },
  {
    currency: "XOF",
    country: "XOF - Cote d'ivoire",
    flag: ciFlag,
    countryCode: "CI",
  },
  {
    currency: "XOF",
    country: "XOF - Benin",
    flag: beninFlag,
    countryCode: "BJ",
  },
  {
    currency: "XOF",
    country: "XOF - Burkina Faso",
    flag: burkinaFlag,
    countryCode: "BF",
  },

  {
    currency: "XOF",
    country: "XOF - Mali",
    flag: maliFlag,
    countryCode: "ML",
  },
  {
    currency: "XOF",
    country: "XOF - Togo",
    flag: togoFlag,
    countryCode: "TG",
  },

  {
    currency: "XOF",
    country: "XOF - Senegal",
    flag: senegalFlag,
    countryCode: "SN",
  },
];

export const currenciesSend = [
  {
    currency: "XOF",
    country: "Cote d'ivoire",
    flag: ciFlag,
    countryCode: "CI",
  },

  {
    currency: "XOF",
    country: "Benin",
    flag: beninFlag,
    countryCode: "BJ",
  },
  {
    currency: "XOF",
    country: "Burkina Faso",
    flag: burkinaFlag,
    countryCode: "BF",
  },

  {
    currency: "XOF",
    country: "Mali",
    flag: maliFlag,
    countryCode: "ML",
  },
  {
    currency: "XOF",
    country: "Togo",
    flag: togoFlag,
    countryCode: "TG",
  },

  {
    currency: "XOF",
    country: "Senegal",
    flag: senegalFlag,
    countryCode: "SN",
  },
  {
    currency: "XAF",
    country: "Cameroun",
    flag: camerounFlag,
    countryCode: "CM",
  },
];
